### ISSUE TITLE
Finalize and Release CVD Resources v1.0

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#106]
As part of OpenJS' grant from the German Sovereign Tech Fund (DE STF), we are going to leverage existing OpenSSF and other resources to develop and publish Coordinated Vulnerability Disclosure (CVD) resources for OpenJS Projects and Node.js Ecosystem Projects.

```[tasklist]
### Guidance Sections
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/109
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/110
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/114
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/115
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/138
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/111
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/116
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/112
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/113
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/117
```
```[tasklist]
### Templates
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/118
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/119
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/107
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/108
```

**Comment by ruddermann** [comment]
https://hackmd.io/abkuwmEuSuC-6qDS23FIsw

https://docs.google.com/document/d/1pFcaTyeTDtngnfdxhFgjZDhD_-dq9vB6UEdozAcO0sU/edit

**Comment by ljharb** [comment]
(i have no access to either, fwiw)

**Comment by ruddermann** [comment]
https://hackmd.io/@rudd/H1R-3yrw0
https://hackmd.io/@rudd/rk4VsgBwC
https://hackmd.io/@rudd/Hym6PM8DC

**Comment by ruddermann** [comment]
These docs have been moved to the OpenJS GitHub: https://github.com/openjs-foundation/security-collab-space/tree/main/CVD_Guide
