### ISSUE TITLE
Establish Workstream 2 Stakeholders and Project Plan

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#120]
As part of OpenJS' grant from the German Sovereign Tech Fund (DE STF), we are going to leverage existing OpenSSF and other resources to develop and publish Coordinated Vulnerability Disclosure (CVD) resources for OpenJS Projects and Node.js Ecosystem Projects.

```[tasklist]
### Tasks
- [ ] Develop Workstream 2 MVSR
- [ ] Initial CVD-Focused Outreach to OpenJS Projects
- [ ] Create Initial Github Milestones/Issues/Tasks/Labels
- [ ] Create Initial Github Project Board(s)
```
