### ISSUE TITLE
Capture OpenJS Project CVD & CVE Insights

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#125]
As part of OpenJS' grant from the German Sovereign Tech Fund (DE STF), we are going to leverage existing OpenSSF and other resources to develop and publish Coordinated Vulnerability Disclosure (CVD) resources for OpenJS Projects and Node.js Ecosystem Projects.

```[tasklist]
### Tasks
- [ ] Gather & Report CVEs Related to OpenJS Projects
- [ ] Capture OpenJS Project Current External CVD State
- [ ] Capture OpenJS Project Teams CVD Experiences and Challenges
```
