### ISSUE TITLE
Priority 1 Projects CVD Guidance Implementation

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#129]
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/130
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/131
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/132
```
