### ISSUE TITLE
Priority 2 Projects CVD Guidance Implementation

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#133]
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/134
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/135
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/136
```
