### ISSUE TITLE
Establish Workstream 1 Stakeholders and Project Plan

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#140]
```[tasklist]
### Tasks
- [ ] Revamp Workstream 1 MVSR
- [ ] Develop OpenJS Project Engagement Plan
- [ ] Update WS1 Github Milestones/Issues/Tasks/Labels
- [ ] Update WS1 Github Project Board(s)
```
