### ISSUE TITLE
Publish & Maintain OpenJS Project Security Dashboards

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#145]
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/147
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/146
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/148
```
