### ISSUE TITLE
Explore Options for Security Dashboard Solution

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#146]
```[tasklist]
### Tasks
- [ ] Dashboard Option: clomonitor.io (CNCF)
- [ ] Dashboard Option: Risk Dashboard (OpenSSF/LF)
- [ ] Dashboard Option: OSS Check (Nearform)
```
