### ISSUE TITLE
Develop JavaScript Resources for Best Practices Badge & Scorecard

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#149]
```[tasklist]
### Tasks
- [ ] Best Practices Badge: Develop Working Draft
- [ ] Scorecard: Develop Working Draft
- [ ] Integrate Scorecard and Badge Resources
- [ ] Publish v1 Resources
```
