### ISSUE TITLE
v2 Security Standards: Explore Improvements

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#151]
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/78
- [x] v1 Comparative Analysis: TBD Security Maturity Models
- [x] v1 Comparative Analysis: Best Practices Badge Levels
- [x] v1 Comparative Analysis: Scorecard Scores
```
