### ISSUE TITLE
Priority 1 Projects Badge & Scorecard Implementation

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#153]
```[tasklist]
### Priority 1 Projects
- [ ] P1 Projects Initially Implement Best Practices Badge
- [ ] P1 Projects Initially Implement OpenSSF Scorecard
- [ ] P1 Projects Badge Level: Pass
- [ ] P1 Projects Badge Level: Silver
- [ ] P1 Projects Badge Level: Gold
```
