### ISSUE TITLE
Priority 2 Projects Best Practices Badge & Scorecard Implementation

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#159]
```[tasklist]
### Tasks
- [ ] P2 Projects Initially Implement Best Practices Badge
- [ ] P2 Projects Initially Implement OpenSSF Scorecard
- [ ] P2 Projects Badge Level: Pass
- [ ] P2 Projects Badge Level: Silver
- [ ] P2 Projects Badge Level: Gold
```
