### ISSUE TITLE
Establish Workstream 3 Stakeholders and Project Plan

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#168]
```[tasklist]
### Tasks
- [ ] Develop Workstream 3 MVSR
- [ ] Build Diverse Panel of WS3 (SBOM) Contributors & Participants
- [ ] Create Initial WS3 Github Milestones/Issues/Tasks/Labels
- [ ] Create Initial WS3 Github Project Board(s)
```
