### ISSUE TITLE
Compliance Report / Audits / Dashboard Created And Populated By Tier 2 Projects

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#17]
```[tasklist]
### Tasks
- [x] Work with CollabSpace to define what criteria should be on the dashboard
- [x] Create Dashboard
- [x] Work with OpenSSF Best Practices WG to discover additional criteria
- [x] Populate dashboard
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/76
```

**Comment by ljharb** [comment]
For the OpenSSF CII Best Practice badge, we'll want to track multiple pieces of info: passing %, silver %, gold %, and which badge is displayed on the readme/website (or none).

**Comment by ljharb** [comment]
Here's an initial dashboard: https://docs.google.com/spreadsheets/d/1wUsWSRu4x_Up4PjVNhEu_z8eOag8V7bcJGaJJl5RlC8/edit#gid=0

Please suggest additional metrics you think should be here, and more will likely surface from the effort on #21.

**Comment by bensternthal** [comment]
@ljharb if you agree... let's get this on the agenda for the next collab space meeting. I'd also suggest adding this into slack so folks (time permitting) can noodle with it prior to Monday.

**Comment by ljharb** [comment]
Sounds great, will do

**Comment by ctcpip** [comment]
LGTM, save for one a11y issue I pointed out via a comment on the doc

**Comment by UlisesGascon** [comment]
LGTM!

**Comment by bensternthal** [comment]
Example dashboard from nearform https://nearform.github.io/osscheck/

**Comment by ljharb** [comment]
The dashboard is partially populated, and work to flesh it out will need to continue over future quarters.

**Comment by ruddermann** [comment]
This issue is being replaced in 2024 by https://github.com/openjs-foundation/security-collab-space/issues/150
