### ISSUE TITLE
Develop & Publish SBOM Resources for OpenJS and JavaScript Projects

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#172]
```[tasklist]
### Tasks
- [ ] Build Prototype Pragmatic SBOM Guidance for OpenJS and JavaScript Projects
- [ ] Publish v1 of Pragmatic SBOM Guidance for OpenJS and JavaScript Projects
- [ ] Document Technical Gaps for SBOMs in OpenJS and JavaScript Projects
- [ ] Document Barriers to SBOMs in OpenJS and JavaScript Projects
- [ ] Publish OpenJS SBOM Observations and Recommendations
```
