### ISSUE TITLE
Establish Workstream 4 Stakeholders and Project Plan

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#178]
```[tasklist]
### Tasks
- [ ] Revamp Workstream 4 MVSR
- [ ] Engage C-SCRM Community for Contributors & Participants
- [ ] Create Initial WS4 Github Milestones/Issues/Tasks/Labels
- [ ] Create Initial WS4 Github Project Board(s)
```
