### ISSUE TITLE
Develop & Publish C-SCRM Resources for OpenJS and JavaScript Projects

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#183]
```[tasklist]
### Tasks
- [ ] Align v1 Secure Release Guidance to C-SCRM Maturity Models
- [ ] Build Prototype of Pragmatic C-SCRM Resources Iteratively using Github Features
- [ ] Publish v1 of Pragmatic C-SCRM Guidance for OpenJS and JavaScript Projects
- [ ] Document Technical Gaps for C-SCRM in OpenJS and JavaScript Projects
- [ ] Document Barriers to C-SCRM in OpenJS and JavaScript Projects
- [ ] Publish OpenJS C-SCRM Observations and Recommendations
```
