### ISSUE TITLE
Milestone: Content Development Update: Customized Best Practices Recommended by Open SSF

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#19]
```[tasklist]
### Tasks
- [x] Publish Best Practices Documents - Scope is Badges & Secure Releases/CVE
- [ ] https://github.com/openjs-foundation/security-collab-space/pull/61
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/18
- [ ] https://github.com/openjs-foundation/security-collab-space/pull/70
```

**Comment by bensternthal** [comment]
Note scope for Q3 is badges and secure releases/CVE

**Comment by ljharb** [comment]
Removing SBOM since it's been tabled for now.
