### ISSUE TITLE
Publish v1 of Pragmatic C-SCRM Guidance for OpenJS and JavaScript Projects

### ISSUE THREAD

**Issue by ruddermann** [openjs-foundation/security-collab-space#195]
```[tasklist]
### Guidance Sections
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/190
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/191
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/192
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/193
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/194
```
