### ISSUE TITLE
Milestone: Broad JS Ecosystem Education & Outreach On OpenSSF Best Practices Badge Program

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#20]
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/22
- [ ] Develop Badge Program Outreach & Communications Plan & Work With Kylie & Get Her Approval
- [ ] Define Badge Program Success Metrics / Goals / Roadmap add to dashboard
- [ ] https://github.com/openjs-foundation/security-collab-space/pull/61
```

**Comment by bensternthal** [comment]
## Potential Badge Program Success Metrics

- adding to incoming projects that they have a badge
- goal to have all projects having a badge
- impact projects having silver by xx
- Goal for quarter would be to have proposal vetted by sec collab space and presented but not necessarily approved by CPC

**Comment by ljharb** [comment]
Filed #61 for the guide.

**Comment by ruddermann** [comment]
This is now being tracked in https://github.com/openjs-foundation/security-collab-space/issues/141
