### ISSUE TITLE
Create Job Description

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/security-collab-space#28]
This ticket tracks finalizing the job description for the Security Champion role.

```[tasklist]
### Tasks
- [x] Draft [job description](https://docs.google.com/document/d/1CFhmS6V75mmRRkf_L7u0nxeErKm7TcF4pPbadt6jTvI/edit#heading=h.3hhomwffiwo7)
- [x] Vet with security working group
- [x] Get salary disclosure information from Owen
- [x] Enter into smart recruiter
- [x] Approved and job posting is live!
```
