### ISSUE TITLE
implement OpenSSF badge for nvm

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/security-collab-space#35]
From #22.
```[tasklist]
### Tasks
- [x] write down my thoughts, friction, and feedback for OpenSSF as I go through it
- [x] make a PR to add the badge to the project, and merge it https://github.com/nvm-sh/nvm/pull/1397
- [ ] Writeup on why this badge is what it is, add to readme
```

**Comment by bensternthal** [comment]
@ljharb can you add a link to the PR where the badge was added? I looked and could not find it.

**Comment by ljharb** [comment]
https://github.com/nvm-sh/nvm/pull/1397
