### ISSUE TITLE
implement OpenSSF badge for fastify

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/security-collab-space#36]
From #22.

```[tasklist]
### Tasks
- [x] file issue/discuss with Fastify maintainers: https://github.com/fastify/fastify/issues/4917
- [x] write down my thoughts, friction, and feedback for OpenSSF as I go through it
- [x] make a PR to add the badge to the project, and merge it (https://github.com/fastify/fastify/pull/4926)
- [ ] https://github.com/fastify/fastify/pull/5111 - Writeup on why this badge is what it is, add to readme
```
