### ISSUE TITLE
Fully populate Foundation Projects Dashboard

### ISSUE THREAD

**Issue by ljharb** [openjs-foundation/security-collab-space#95]
Fully populate the [dashboard](https://docs.google.com/spreadsheets/d/1wUsWSRu4x_Up4PjVNhEu_z8eOag8V7bcJGaJJl5RlC8/edit#gid=0).
```[tasklist]
### Tasks
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/94
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/92
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/93
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/73
- [ ] https://github.com/openjs-foundation/security-collab-space/issues/96
```

**Comment by ruddermann** [comment]
Issue is being replaced for 2024 by https://github.com/openjs-foundation/security-collab-space/issues/145
